services:
  mysql-source:
    image: mysql:latest
    container_name: blisgo-db-source
    environment:
      - MYSQL_DATABASE=blisgo
      - MYSQL_ROOT_PASSWORD=root
      - SERVER_ID=1
      - LOG_BIN=mysql-bin
    ports:
      - 3306:3306
    restart: always

  mysql-replica:
    depends_on:
      - mysql-source
    image: mysql:latest
    container_name: blisgo-db-replica
    environment:
      - MYSQL_DATABASE=blisgo
      - MYSQL_ROOT_PASSWORD=root
      - SERVER_ID=2
      - LOG_BIN=mysql-bin
      - RELAY_LOG=mysql-relay-bin
    ports:
      - 3307:3306
    restart: always

  redis:
    image: redis:latest
    container_name: blisgo-documents
    ports:
      - 6379:6379

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: blisgo-prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    restart: unless-stopped
#    ports:
#      - 9090:9090
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: blisgo-grafana
#    ports:
#      - 3000:3000
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_USERS_ALLOW_SIGN_UP=false
#      - GF_USERS_ALLOW_ORG_CREATE=false
#    volumes:
#      - ./grafana:/var/lib/grafana
#    restart: unless-stopped

networks:
  network: