services:
  mysql:
    image: mysql:latest
    container_name: blisgo-db
    environment:
      - MYSQL_DATABASE=blisgo
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: blisgo-documents
    ports:
      - 6379:6379

networks:
  network: