SET @member_id = UNHEX(REPLACE('4c29cb26-d2f3-38d8-9d02-a9da30c7ad99', '-', ''));

INSERT INTO reply (post_id, content, member_id)
VALUES (1, 'comment 1.', @member_id),
       (1, 'comment 2.', @member_id),
       (1, 'comment 3.', @member_id),
       (1, 'comment 4.', @member_id),
       (1, 'comment 5.', @member_id),
       (1, 'comment 6.', @member_id),
       (1, 'comment 7.', @member_id),
       (1, 'comment 8.', @member_id),
       (1, 'comment 9.', @member_id),
       (1, 'comment 10.', @member_id),
       (1, 'comment 11.', @member_id),
       (1, 'comment 12.', @member_id),
       (1, 'comment 13.', @member_id),
       (1, 'comment 14.', @member_id),
       (1, 'comment 15.', @member_id),
       (1, 'comment 16.', @member_id),
       (1, 'comment 17.', @member_id),
       (1, 'comment 18.', @member_id),
       (1, 'comment 19.', @member_id),
       (1, 'comment 20.', @member_id),
       (1, 'comment 21.', @member_id),
       (1, 'comment 22.', @member_id),
       (1, 'comment 23.', @member_id),
       (1, 'comment 24.', @member_id),
       (1, 'comment 25.', @member_id),
       (1, 'comment 26.', @member_id),
       (1, 'comment 27.', @member_id),
       (1, 'comment 28.', @member_id),
       (1, 'comment 29.', @member_id),
       (1, 'comment 30.', @member_id),
       (1, 'comment 31.', @member_id),
       (1, 'comment 32.', @member_id),
       (1, 'comment 33.', @member_id),
       (1, 'comment 34.', @member_id),
       (1, 'comment 35.', @member_id),
       (1, 'comment 36.', @member_id),
       (1, 'comment 37.', @member_id),
       (1, 'comment 38.', @member_id),
       (1, 'comment 39.', @member_id),
       (1, 'comment 40.', @member_id);