okta:
  oauth2:
    issuer: https://${AUTH0_DOMAIN}/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    audience: https://${AUTH0_DOMAIN}/userinfo

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
  session:
    redis:
      namespace: spring:session

server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
        secure: true
      timeout: 3600

    encoding:
      enabled: true
      force: true
      charset: UTF-8

  error:
    include-stacktrace: ALWAYS
    include-exception: true
    path: /error
    whitelabel:
      enabled: true
  compression:
    enabled: true