spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDISHOST}
      username: ${REDISUSER}
      password: ${REDISPASSWORD}
      port: ${REDISPORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:${MYSQL_URL}"
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  thymeleaf:
    cache: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: on
    locations: classpath:db/migration
    url: "jdbc:${MYSQL_URL}"
    user: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false

server:
  servlet:
    session:
      cookie:
        domain: ${DOMAIN}