spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      source:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: "jdbc:mysql://localhost:3306/blisgo"
        read-only: false
        username: root
        password: root
        port: 3306
      replica:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: "jdbc:mysql://localhost:3307/blisgo"
        read-only: true
        username: root
        password: root
        port: 3307
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
      ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  thymeleaf:
    cache: false
  data:
    redis:
      host: localhost
      port: 6379

  docker:
    compose:
      enabled: true

server:
  servlet:
    session:
      cookie:
        domain: localhost