spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates
    check-template-location: true
    suffix: .html
    mode: HTML
  servlet:
    multipart:
      maxRequestSize: 10MB
      maxFileSize: 10MB
  messages:
    encoding: UTF-8